<?php

namespace Cintas\Models\Items;

use Cintas\Models\AbstractModel;
use Cintas\Models\Facility\TargetContainer;

class ProductType extends AbstractModel
{
    //
    public function getLabelAttribute($value)
    {
        return $this->name ?? parent::getLabelAttribute($value); // TODO: Change the autogenerated stub
    }


    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function target_containers()
    {
        return $this->belongsToMany(TargetContainer::class)->withPivot(['target_container_content']);
    }

}
